In [16]:
import pandas as pd
import os
import re

# Path to your folder
folder_path = 'outputs'

# Initialize lists to hold DataFrames
dfs_it = []
dfs_es = []

# Regex to match only non-duplicate files like 'IT_123.csv' or 'ES_456.csv'
valid_file_pattern = re.compile(r'^(IT|ES)_(\d+)\.csv$')

# Iterate over files in the folder
for filename in os.listdir(folder_path):
    if valid_file_pattern.match(filename):
        full_path = os.path.join(folder_path, filename)

        # Read CSV with datetime index
        df = pd.read_csv(full_path, index_col=0, parse_dates=True)

        # Append to the appropriate list
        if filename.startswith('IT_'):
            dfs_it.append(df)
        else:  # starts with ES_
            dfs_es.append(df)

# Combine all dataframes by column
df_it = pd.concat(dfs_it, axis=1)
df_es = pd.concat(dfs_es, axis=1)

In [18]:
df_it

,VALUEMWHMETERINGDATA_customerIT_1027,VALUEMWHMETERINGDATA_customerIT_2248,VALUEMWHMETERINGDATA_customerIT_1755,VALUEMWHMETERINGDATA_customerIT_387,VALUEMWHMETERINGDATA_customerIT_393,VALUEMWHMETERINGDATA_customerIT_2260,VALUEMWHMETERINGDATA_customerIT_1769,VALUEMWHMETERINGDATA_customerIT_2506,VALUEMWHMETERINGDATA_customerIT_1782,VALUEMWHMETERINGDATA_customerIT_378,...,VALUEMWHMETERINGDATA_customerIT_2292,VALUEMWHMETERINGDATA_customerIT_407,VALUEMWHMETERINGDATA_customerIT_1016,VALUEMWHMETERINGDATA_customerIT_1770,VALUEMWHMETERINGDATA_customerIT_2279,VALUEMWHMETERINGDATA_customerIT_1764,VALUEMWHMETERINGDATA_customerIT_1002,VALUEMWHMETERINGDATA_customerIT_2523,VALUEMWHMETERINGDATA_customerIT_1758,VALUEMWHMETERINGDATA_customerIT_2537
2024-08-01 00:00:00,0.000815,0.0,0.000314,0.191241,0.283035,0.003919,0.000223,0.139380,0.000719,0.041940,...,0.003897,0.582591,0.330784,0.000273,0.004320,0.000126,0.000720,0.000260,0.000436,0.207372
2024-08-01 01:00:00,0.000854,0.0,0.000283,0.210290,0.288403,0.003910,0.000208,0.229559,0.000667,0.048131,...,0.007937,0.565081,0.307351,0.000305,0.004427,0.000165,0.000819,0.000319,0.000437,0.179540
2024-08-01 02:00:00,0.000950,0.0,0.000278,0.222569,0.329723,0.003973,0.000203,0.238182,0.000712,0.045606,...,0.005617,0.541131,0.314273,0.000249,0.004875,0.000183,0.000770,0.000258,0.000431,0.201326
2024-08-01 03:00:00,0.000690,0.0,0.000242,0.249673,0.367797,0.003951,0.000185,0.196468,0.000685,0.048041,...,0.003503,0.554918,0.299384,0.000293,0.004727,0.000132,0.000461,0.000258,0.000434,0.223657
2024-08-01 04:00:00,0.000722,0.0,0.000230,0.393137,0.429629,0.003938,0.000209,0.319521,0.000668,0.046067,...,0.005412,0.540931,0.319925,0.000255,0.007615,0.000182,0.001835,0.000310,0.000449,0.271943
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-31 19:00:00,0.000843,0.0,0.000470,0.372091,0.566483,0.003782,0.000174,0.327585,0.000573,0.021241,...,0.037162,0.634933,0.298565,0.000318,0.008016,0.000112,0.000540,0.000334,0.000632,0.405361
2024-08-31 20:00:00,0.001111,0.0,0.000347,0.375789,0.557006,0.003931,0.000173,0.313066,0.000852,0.025736,...,0.038710,0.586573,0.305688,0.000368,0.013260,0.000118,0.000662,0.000314,0.000534,0.393959
2024-08-31 21:00:00,0.000749,0.0,0.000311,0.437820,0.543390,0.003922,0.000313,0.277896,0.000931,0.026395,...,0.021217,0.632820,0.297012,0.000316,0.012031,0.000114,0.001359,0.000305,0.000536,0.333553
2024-08-31 22:00:00,0.000775,0.0,0.000346,0.403833,0.412817,0.003904,0.000252,0.394040,0.000897,0.026507,...,0.058954,0.634493,0.218438,0.000316,0.019152,0.000101,0.000882,0.000336,0.000570,0.322832
2024-08-31 23:00:00,0.000710,0.0,0.000262,0.407235,0.369849,0.003882,0.000219,0.326159,0.000891,0.026484,...,0.056912,0.674008,0.197691,0.000308,0.019056,0.000088,0.001300,0.000267,0.000508,0.328088

In [17]:
df_es

,VALUEMWHMETERINGDATA_customerES_202,VALUEMWHMETERINGDATA_customerES_216,VALUEMWHMETERINGDATA_customerES_148,VALUEMWHMETERINGDATA_customerES_175,VALUEMWHMETERINGDATA_customerES_201,VALUEMWHMETERINGDATA_customerES_30,VALUEMWHMETERINGDATA_customerES_188,VALUEMWHMETERINGDATA_customerES_162,VALUEMWHMETERINGDATA_customerES_19,VALUEMWHMETERINGDATA_customerES_31,...,VALUEMWHMETERINGDATA_customerES_180,VALUEMWHMETERINGDATA_customerES_209,VALUEMWHMETERINGDATA_customerES_225,VALUEMWHMETERINGDATA_customerES_190,VALUEMWHMETERINGDATA_customerES_226,VALUEMWHMETERINGDATA_customerES_232,VALUEMWHMETERINGDATA_customerES_151,VALUEMWHMETERINGDATA_customerES_179,VALUEMWHMETERINGDATA_customerES_186,VALUEMWHMETERINGDATA_customerES_5
2024-08-01 00:00:00,0.184332,0.000779,0.027748,0.000036,0.000293,0.015622,0.000033,0.030138,3.082833,0.006362,...,0.003661,0.148253,0.000201,0.083770,0.000171,1.895103,0.141290,0.043980,0.000814,0.022273
2024-08-01 01:00:00,0.191955,0.000897,0.029365,0.000040,0.000387,0.016108,0.000059,0.034649,3.031257,0.006454,...,0.005497,0.116567,0.000326,0.094442,0.000082,1.913374,0.126303,0.039922,0.001372,0.022910
2024-08-01 02:00:00,0.191376,0.000804,0.030773,0.000032,0.000349,0.015241,0.000057,0.034324,3.107730,0.005885,...,0.004800,0.104349,0.000357,0.092436,0.000138,1.907244,0.150421,0.068251,0.000489,0.021643
2024-08-01 03:00:00,0.199981,0.001002,0.036216,0.000031,0.000421,0.024621,0.000079,0.032138,3.046230,0.006456,...,0.006040,0.127504,0.000330,0.089410,0.000122,1.907105,0.177246,0.101850,0.000856,0.024716
2024-08-01 04:00:00,0.201803,0.000810,0.034714,0.000023,0.000536,0.022929,0.000113,0.037356,3.009387,0.006704,...,0.006166,0.170400,0.000388,0.101330,0.000154,1.945822,0.195698,0.139729,0.000269,0.024042
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-31 19:00:00,0.127661,0.000760,0.018395,0.000033,0.001982,0.014767,0.000050,0.018871,2.083657,0.007064,...,0.006466,0.098828,0.000423,0.077413,0.000486,2.179645,0.036420,0.026939,0.000969,0.023792
2024-08-31 20:00:00,0.136107,0.000853,0.020934,0.000032,0.001054,0.016657,0.000035,0.024121,2.069520,0.007253,...,0.006855,0.120006,0.000394,0.077913,0.000371,2.215290,0.041921,0.026153,0.001293,0.022869
2024-08-31 21:00:00,0.146287,0.000937,0.023597,0.000033,0.000513,0.019494,0.000028,0.023228,1.973580,0.008476,...,0.010170,0.098498,0.000310,0.084143,0.000244,2.217390,0.043202,0.023714,0.000705,0.024646
2024-08-31 22:00:00,0.124079,0.000909,0.027483,0.000039,0.000804,0.018629,0.000056,0.014193,2.356282,0.008458,...,0.008628,0.110939,0.000511,0.090270,0.000377,2.207583,0.066107,0.028766,0.000707,0.022383
2024-08-31 23:00:00,0.137537,0.000620,0.031300,0.000043,0.001000,0.022021,0.000040,0.020433,2.501794,0.008207,...,0.004001,0.363239,0.000517,0.086758,0.000280,2.206587,0.041650,0.033055,0.000942,0.022811

In [3]:
df_it.shape

(744, 1696)

In [4]:
df_es.shape

(744, 98)

In [22]:
import pandas as pd
import numpy as np
from os.path import join
from datetime import datetime

date_format = '%Y-%m-%d %H:%M:%S'
student_path = r"my_outputs"
testing_set_path = r"datasets2025"

absolute_error = {}
portfolio_error = {} 

import pandas as pd
import numpy as np
from os.path import join

# depending on your IDE, you might need to add datathon_eth. in front of data
from my_data_og import DataLoader, SimpleEncoding

# depending on your IDE, you might need to add datathon_eth. in front of forecast_models
from forecast_og_models import SimpleModel


team_name = "HANGUK_ML"
country = "IT"
zone = country
# Inputs
input_path = r"datasets2025"
output_path = r"my_outputs"

# Load Datasets
loader = DataLoader(input_path)
# features are holidays and temperature
training_set, features, example_results = loader.load_data(zone)
training_set_it = training_set

"""
EVERYTHING STARTING FROM HERE CAN BE MODIFIED.
"""
# team_name = "OurCoolTeamName"
# Data Manipulation and Training
start_training = training_set.index.min()
end_training = training_set.index.max()
start_forecast, end_forecast = example_results.index[0], example_results.index[-1]

range_forecast = pd.date_range(start=start_forecast, end=end_forecast, freq="1H")
forecast = df_it[training_set_it.columns]
# forecast = pd.DataFrame(columns=training_set.columns, index=range_forecast)

# for costumer in training_set.columns.values:
#     print(costumer)
#     consumption = training_set.loc[:, costumer]
    
#     feature_dummy = features['temp'].loc[start_training:]

#     encoding = SimpleEncoding(
#         consumption, feature_dummy, end_training, start_forecast, end_forecast
#     )

#     feature_past, feature_future, consumption_clean = (
#         encoding.meta_encoding()
#     )

#     # Train
#     model = SimpleModel()
#     model.train(feature_past, consumption_clean)

#     # Predict
#     output = model.predict(feature_future)
#     forecast[costumer] = output

"""
END OF THE MODIFIABLE PART.
"""

# test to make sure that the output has the expected shape.
dummy_error = np.abs(forecast - example_results).sum().sum()
assert np.all(forecast.columns == example_results.columns), (
    "Wrong header or header order."
)
assert np.all(forecast.index == example_results.index), (
    "Wrong index or index order."
)
assert isinstance(dummy_error, np.float64), "Wrong dummy_error type."
assert forecast.isna().sum().sum() == 0, "NaN in forecast."

forecast.to_csv(
    join(output_path, "students_results_" + team_name + "_" + country + ".csv")
)
forecast_it = forecast

/var/folders/3b/v9q3pbyx1r1gb74yk77xgx900000gq/T/ipykernel_13457/876791797.py:46: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  range_forecast = pd.date_range(start=start_forecast, end=end_forecast, freq="1H")

In [8]:
forecast

,VALUEMWHMETERINGDATA_customerIT_1,VALUEMWHMETERINGDATA_customerIT_2,VALUEMWHMETERINGDATA_customerIT_3,VALUEMWHMETERINGDATA_customerIT_4,VALUEMWHMETERINGDATA_customerIT_5,VALUEMWHMETERINGDATA_customerIT_6,VALUEMWHMETERINGDATA_customerIT_7,VALUEMWHMETERINGDATA_customerIT_8,VALUEMWHMETERINGDATA_customerIT_13,VALUEMWHMETERINGDATA_customerIT_14,...,VALUEMWHMETERINGDATA_customerIT_2832,VALUEMWHMETERINGDATA_customerIT_2836,VALUEMWHMETERINGDATA_customerIT_2844,VALUEMWHMETERINGDATA_customerIT_2845,VALUEMWHMETERINGDATA_customerIT_2847,VALUEMWHMETERINGDATA_customerIT_2848,VALUEMWHMETERINGDATA_customerIT_2849,VALUEMWHMETERINGDATA_customerIT_2850,VALUEMWHMETERINGDATA_customerIT_2851,VALUEMWHMETERINGDATA_customerIT_2852
2024-08-01 00:00:00,0.001932,0.000882,0.181204,0.462359,0.001670,0.316828,0.212403,0.025316,0.002672,0.001782,...,0.005046,0.070378,0.000549,2.302734,0.035155,0.006855,0.005243,0.061807,0.000133,0.031759
2024-08-01 01:00:00,0.000274,0.000950,0.202876,0.435892,0.003348,0.284867,0.177757,0.041546,0.002795,0.002167,...,0.005090,0.083196,0.000718,2.072714,0.036258,0.006687,0.005740,0.057734,0.000744,0.020796
2024-08-01 02:00:00,0.000668,0.000513,0.195306,0.426013,0.002810,0.298421,0.163757,0.034646,0.002839,0.002219,...,0.002925,0.079638,0.000603,2.308071,0.034895,0.006025,0.007240,0.059975,0.000906,0.018696
2024-08-01 03:00:00,0.001367,0.000933,0.194591,0.435872,0.001681,0.283844,0.157498,0.025293,0.002825,0.001994,...,0.005243,0.084768,0.000683,2.150324,0.035235,0.006202,0.004991,0.054781,0.000422,0.019985
2024-08-01 04:00:00,0.003268,0.001115,0.190363,0.402430,0.003191,0.296579,0.171167,0.054368,0.002869,0.002265,...,0.005334,0.102186,0.000480,2.323963,0.035375,0.006358,0.007014,0.053276,0.001640,0.022081
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-31 19:00:00,0.004524,0.015198,0.203912,0.244851,0.010043,0.168133,0.209566,0.020213,0.002918,0.001569,...,0.005205,0.108627,0.001408,1.649645,0.040722,0.007283,0.004842,0.073566,0.000620,0.019042
2024-08-31 20:00:00,0.003139,0.007035,0.194201,0.336350,0.002097,0.201143,0.211069,0.026542,0.002912,0.001996,...,0.004265,0.116716,0.001460,1.864070,0.041974,0.007181,0.005719,0.066652,0.001076,0.019416
2024-08-31 21:00:00,0.002290,0.002754,0.193916,0.373430,0.000866,0.199956,0.195423,0.029079,0.002845,0.001920,...,0.009913,0.118290,0.003574,1.803777,0.039995,0.006780,0.004403,0.063608,0.001209,0.017823
2024-08-31 22:00:00,0.003556,0.011463,0.195533,0.347351,0.015511,0.196871,0.220079,0.032119,0.002887,0.001641,...,0.010954,0.121428,0.004157,1.811571,0.042694,0.007366,0.005620,0.056482,0.000824,0.022343
2024-08-31 23:00:00,0.002806,0.017910,0.177845,0.409286,0.014410,0.201280,0.217143,0.019534,0.003005,0.001506,...,0.013126,0.107488,0.004372,1.621168,0.040302,0.007548,0.008845,0.065977,0.000991,0.021110

In [64]:
forecast_it

,VALUEMWHMETERINGDATA_customerIT_1,VALUEMWHMETERINGDATA_customerIT_2,VALUEMWHMETERINGDATA_customerIT_3,VALUEMWHMETERINGDATA_customerIT_4,VALUEMWHMETERINGDATA_customerIT_5,VALUEMWHMETERINGDATA_customerIT_6,VALUEMWHMETERINGDATA_customerIT_7,VALUEMWHMETERINGDATA_customerIT_8,VALUEMWHMETERINGDATA_customerIT_13,VALUEMWHMETERINGDATA_customerIT_14,...,VALUEMWHMETERINGDATA_customerIT_2832,VALUEMWHMETERINGDATA_customerIT_2836,VALUEMWHMETERINGDATA_customerIT_2844,VALUEMWHMETERINGDATA_customerIT_2845,VALUEMWHMETERINGDATA_customerIT_2847,VALUEMWHMETERINGDATA_customerIT_2848,VALUEMWHMETERINGDATA_customerIT_2849,VALUEMWHMETERINGDATA_customerIT_2850,VALUEMWHMETERINGDATA_customerIT_2851,VALUEMWHMETERINGDATA_customerIT_2852
2024-08-01 00:00:00,0.001932,0.000882,0.181204,0.462359,0.001670,0.316828,0.212403,0.025316,0.002672,0.001782,...,0.005046,0.070378,0.000549,2.302734,0.035155,0.006855,0.005243,0.061807,0.000133,0.031759
2024-08-01 01:00:00,0.000274,0.000950,0.202876,0.435892,0.003348,0.284867,0.177757,0.041546,0.002795,0.002167,...,0.005090,0.083196,0.000718,2.072714,0.036258,0.006687,0.005740,0.057734,0.000744,0.020796
2024-08-01 02:00:00,0.000668,0.000513,0.195306,0.426013,0.002810,0.298421,0.163757,0.034646,0.002839,0.002219,...,0.002925,0.079638,0.000603,2.308071,0.034895,0.006025,0.007240,0.059975,0.000906,0.018696
2024-08-01 03:00:00,0.001367,0.000933,0.194591,0.435872,0.001681,0.283844,0.157498,0.025293,0.002825,0.001994,...,0.005243,0.084768,0.000683,2.150324,0.035235,0.006202,0.004991,0.054781,0.000422,0.019985
2024-08-01 04:00:00,0.003268,0.001115,0.190363,0.402430,0.003191,0.296579,0.171167,0.054368,0.002869,0.002265,...,0.005334,0.102186,0.000480,2.323963,0.035375,0.006358,0.007014,0.053276,0.001640,0.022081
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-31 19:00:00,0.004524,0.015198,0.203912,0.244851,0.010043,0.168133,0.209566,0.020213,0.002918,0.001569,...,0.005205,0.108627,0.001408,1.649645,0.040722,0.007283,0.004842,0.073566,0.000620,0.019042
2024-08-31 20:00:00,0.003139,0.007035,0.194201,0.336350,0.002097,0.201143,0.211069,0.026542,0.002912,0.001996,...,0.004265,0.116716,0.001460,1.864070,0.041974,0.007181,0.005719,0.066652,0.001076,0.019416
2024-08-31 21:00:00,0.002290,0.002754,0.193916,0.373430,0.000866,0.199956,0.195423,0.029079,0.002845,0.001920,...,0.009913,0.118290,0.003574,1.803777,0.039995,0.006780,0.004403,0.063608,0.001209,0.017823
2024-08-31 22:00:00,0.003556,0.011463,0.195533,0.347351,0.015511,0.196871,0.220079,0.032119,0.002887,0.001641,...,0.010954,0.121428,0.004157,1.811571,0.042694,0.007366,0.005620,0.056482,0.000824,0.022343
2024-08-31 23:00:00,0.002806,0.017910,0.177845,0.409286,0.014410,0.201280,0.217143,0.019534,0.003005,0.001506,...,0.013126,0.107488,0.004372,1.621168,0.040302,0.007548,0.008845,0.065977,0.000991,0.021110

In [23]:
import pandas as pd
import numpy as np
from os.path import join

# depending on your IDE, you might need to add datathon_eth. in front of data
from my_data_og import DataLoader, SimpleEncoding

# depending on your IDE, you might need to add datathon_eth. in front of forecast_models
from forecast_og_models import SimpleModel


team_name = "HANGUK_ML"
country = "ES"
zone = country
# Inputs
input_path = r"datasets2025"
output_path = r"my_outputs"

# Load Datasets
loader = DataLoader(input_path)
# features are holidays and temperature
training_set, features, example_results = loader.load_data(zone)
training_set_es = training_set

"""
EVERYTHING STARTING FROM HERE CAN BE MODIFIED.
"""
# team_name = "OurCoolTeamName"
# Data Manipulation and Training
start_training = training_set.index.min()
end_training = training_set.index.max()
start_forecast, end_forecast = example_results.index[0], example_results.index[-1]

range_forecast = pd.date_range(start=start_forecast, end=end_forecast, freq="1H")
forecast = df_es[training_set.columns]
# forecast = pd.DataFrame(columns=training_set.columns, index=range_forecast)

# for costumer in training_set.columns.values:
#     print(costumer)
#     consumption = training_set.loc[:, costumer]
    
#     feature_dummy = features['temp'].loc[start_training:]

#     encoding = SimpleEncoding(
#         consumption, feature_dummy, end_training, start_forecast, end_forecast
#     )

#     feature_past, feature_future, consumption_clean = (
#         encoding.meta_encoding()
#     )

#     # Train
#     model = SimpleModel()
#     model.train(feature_past, consumption_clean)

#     # Predict
#     output = model.predict(feature_future)
#     forecast[costumer] = output

"""
END OF THE MODIFIABLE PART.
"""

# test to make sure that the output has the expected shape.
dummy_error = np.abs(forecast - example_results).sum().sum()
assert np.all(forecast.columns == example_results.columns), (
    "Wrong header or header order."
)
assert np.all(forecast.index == example_results.index), (
    "Wrong index or index order."
)
assert isinstance(dummy_error, np.float64), "Wrong dummy_error type."
assert forecast.isna().sum().sum() == 0, "NaN in forecast."
print(join(output_path, "students_results_" + team_name + "_" + country + ".csv"))
forecast.to_csv(
    join(output_path, "students_results_" + team_name + "_" + country + ".csv")
)
forecast_es = forecast

my_outputs/students_results_HANGUK_ML_ES.csv

/var/folders/3b/v9q3pbyx1r1gb74yk77xgx900000gq/T/ipykernel_13457/2336089537.py:34: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  range_forecast = pd.date_range(start=start_forecast, end=end_forecast, freq="1H")

In [20]:
forecast_es

,VALUEMWHMETERINGDATA_customerES_1,VALUEMWHMETERINGDATA_customerES_2,VALUEMWHMETERINGDATA_customerES_5,VALUEMWHMETERINGDATA_customerES_11,VALUEMWHMETERINGDATA_customerES_19,VALUEMWHMETERINGDATA_customerES_30,VALUEMWHMETERINGDATA_customerES_31,VALUEMWHMETERINGDATA_customerES_39,VALUEMWHMETERINGDATA_customerES_40,VALUEMWHMETERINGDATA_customerES_44,...,VALUEMWHMETERINGDATA_customerES_297,VALUEMWHMETERINGDATA_customerES_298,VALUEMWHMETERINGDATA_customerES_300,VALUEMWHMETERINGDATA_customerES_307,VALUEMWHMETERINGDATA_customerES_311,VALUEMWHMETERINGDATA_customerES_312,VALUEMWHMETERINGDATA_customerES_313,VALUEMWHMETERINGDATA_customerES_334,VALUEMWHMETERINGDATA_customerES_335,VALUEMWHMETERINGDATA_customerES_336
2024-08-01 00:00:00,0.001112,0.000139,0.022273,0.020370,3.082833,0.015622,0.006362,0.085236,0.041503,0.076010,...,0.008825,1.102922,0.003942,2.004439,0.135572,0.003531,0.027683,0.052869,0.027916,0.136876
2024-08-01 01:00:00,0.001545,0.000231,0.022910,0.019932,3.031257,0.016108,0.006454,0.086591,0.040539,0.075502,...,0.007123,1.098390,0.003775,1.647362,0.108615,0.004409,0.032838,0.031133,0.026959,0.156864
2024-08-01 02:00:00,0.001740,0.000203,0.021643,0.021465,3.107730,0.015241,0.005885,0.155572,0.042450,0.085260,...,0.006783,1.101998,0.003315,1.772872,0.160863,0.004586,0.038473,0.051002,0.025568,0.148842
2024-08-01 03:00:00,0.002034,0.000246,0.024716,0.018598,3.046230,0.024621,0.006456,0.213295,0.044702,0.098411,...,0.007115,1.078395,0.003616,2.102226,0.198137,0.005106,0.039873,0.049824,0.025348,0.167505
2024-08-01 04:00:00,0.001398,0.000119,0.024042,0.026208,3.009387,0.022929,0.006704,0.246551,0.043410,0.090442,...,0.007809,1.103906,0.003334,2.530491,0.123386,0.006676,0.048136,0.046980,0.024691,0.177338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-31 19:00:00,0.001384,0.000166,0.023792,0.021666,2.083657,0.014767,0.007064,0.084786,0.025139,0.079229,...,0.008014,1.102792,0.003882,1.023127,0.081560,0.005872,0.039384,0.060226,0.025346,0.107484
2024-08-31 20:00:00,0.001481,0.000170,0.022869,0.025111,2.069520,0.016657,0.007253,0.074493,0.026410,0.066961,...,0.010178,1.019971,0.003546,1.603679,0.113702,0.004458,0.021759,0.053097,0.023541,0.126779
2024-08-31 21:00:00,0.001745,0.000190,0.024646,0.021621,1.973580,0.019494,0.008476,0.070645,0.026696,0.064557,...,0.009157,0.530609,0.003644,1.550535,0.126150,0.005076,0.027948,0.048797,0.023234,0.128125
2024-08-31 22:00:00,0.002049,0.000238,0.022383,0.023594,2.356282,0.018629,0.008458,0.064076,0.026131,0.054090,...,0.006114,0.902513,0.003971,1.476234,0.080737,0.005441,0.026798,0.030175,0.021483,0.127928
2024-08-31 23:00:00,0.002542,0.000314,0.022811,0.019062,2.501794,0.022021,0.008207,0.072091,0.027867,0.072288,...,0.007290,0.792733,0.003849,1.721110,0.094619,0.005007,0.026778,0.026511,0.025742,0.116717

In [24]:
for team_name in ['HANGUK_ML']:

    # try:
    for country in ['ES', 'IT']:
        student_solution_path = join(
            student_path, "students_results_" + team_name + '_' + country + ".csv")
        student_solution = pd.read_csv(
            student_solution_path, index_col=0, parse_dates=True, date_format=date_format)
        # student_soluion = 
        # if country == 'ES': student_solution = forecast_es
        # elif country == 'IT': student_solution = forecast_it


        testing_set_fullpath = join(
            testing_set_path, "example_set_" + country + ".csv")
        testing_set = pd.read_csv(
            testing_set_fullpath, index_col=0, parse_dates=True, date_format=date_format)

        print(f"Student solution columns: {student_solution.shape[1]}")
        print(f"Student solution columns: {student_solution.columns}")
        print(f"Testing set columns: {testing_set.shape[1]}")
        print(f"Column difference: {set(student_solution.columns) ^ set(testing_set.columns)}")

        country_error = (student_solution - testing_set).abs().sum().sum()
        portfolio_country_error = (student_solution - testing_set).sum(axis=1).abs().sum() 

        assert np.all(student_solution.columns ==
                        testing_set.columns), 'Wrong header or header order for team ' + team_name
        print(f"Length of student solution: {len(student_solution.index)}")
        print(f"Length of testing solution: {len(testing_set.index)}")
        assert np.all(student_solution.index ==
                        testing_set.index), 'Wrong index or index order for team ' + team_name
        assert isinstance(
            country_error, np.float64), 'Wrong error type for team ' + team_name
        assert student_solution.isna().sum().sum(
        ) == 0, 'NaN in forecast for team ' + team_name

        absolute_error[country] = country_error
        portfolio_error[country] = portfolio_country_error

    forecast_score = (
        1.0*absolute_error['IT'] + 5.0*absolute_error['ES'] + 
        10.0*portfolio_error['IT'] + 50.0*portfolio_error['ES']
    )
    print('The team ' + team_name + ' reached a forecast score of ' +
            str(np.round(forecast_score, 0)))
#     except Exception as e:
#         print('Error for team ' + team_name)
#         print(e)
# print('=== End of the script, %s. ===' % (str(datetime.now())))

Student solution columns: 98
Student solution columns: Index(['VALUEMWHMETERINGDATA_customerES_1',
       'VALUEMWHMETERINGDATA_customerES_2',
       'VALUEMWHMETERINGDATA_customerES_5',
       'VALUEMWHMETERINGDATA_customerES_11',
       'VALUEMWHMETERINGDATA_customerES_19',
       'VALUEMWHMETERINGDATA_customerES_30',
       'VALUEMWHMETERINGDATA_customerES_31',
       'VALUEMWHMETERINGDATA_customerES_39',
       'VALUEMWHMETERINGDATA_customerES_40',
       'VALUEMWHMETERINGDATA_customerES_44',
       'VALUEMWHMETERINGDATA_customerES_45',
       'VALUEMWHMETERINGDATA_customerES_46',
       'VALUEMWHMETERINGDATA_customerES_48',
       'VALUEMWHMETERINGDATA_customerES_59',
       'VALUEMWHMETERINGDATA_customerES_60',
       'VALUEMWHMETERINGDATA_customerES_61',
       'VALUEMWHMETERINGDATA_customerES_62',
       'VALUEMWHMETERINGDATA_customerES_63',
       'VALUEMWHMETERINGDATA_customerES_64',
       'VALUEMWHMETERINGDATA_customerES_66',
       'VALUEMWHMETERINGDATA_customerES_67',
       'VALUEMWHMETERINGDATA_customerES_69',
       'VALUEMWHMETERINGDATA_customerES_70',
       'VALUEMWHMETERINGDATA_customerES_72',
       'VALUEMWHMETERINGDATA_customerES_74',
       'VALUEMWHMETERINGDATA_customerES_76',
       'VALUEMWHMETERINGDATA_customerES_80',
       'VALUEMWHMETERINGDATA_customerES_89',
       'VALUEMWHMETERINGDATA_customerES_90',
       'VALUEMWHMETERINGDATA_customerES_92',
       'VALUEMWHMETERINGDATA_customerES_93',
       'VALUEMWHMETERINGDATA_customerES_94',
       'VALUEMWHMETERINGDATA_customerES_96',
       'VALUEMWHMETERINGDATA_customerES_97',
       'VALUEMWHMETERINGDATA_customerES_98',
       'VALUEMWHMETERINGDATA_customerES_100',
       'VALUEMWHMETERINGDATA_customerES_104',
       'VALUEMWHMETERINGDATA_customerES_107',
       'VALUEMWHMETERINGDATA_customerES_109',
       'VALUEMWHMETERINGDATA_customerES_114',
       'VALUEMWHMETERINGDATA_customerES_115',
       'VALUEMWHMETERINGDATA_customerES_117',
       'VALUEMWHMETERINGDATA_customerES_126',
       'VALUEMWHMETERINGDATA_customerES_127',
       'VALUEMWHMETERINGDATA_customerES_129',
       'VALUEMWHMETERINGDATA_customerES_130',
       'VALUEMWHMETERINGDATA_customerES_140',
       'VALUEMWHMETERINGDATA_customerES_143',
       'VALUEMWHMETERINGDATA_customerES_148',
       'VALUEMWHMETERINGDATA_customerES_151',
       'VALUEMWHMETERINGDATA_customerES_154',
       'VALUEMWHMETERINGDATA_customerES_162',
       'VALUEMWHMETERINGDATA_customerES_164',
       'VALUEMWHMETERINGDATA_customerES_167',
       'VALUEMWHMETERINGDATA_customerES_169',
       'VALUEMWHMETERINGDATA_customerES_175',
       'VALUEMWHMETERINGDATA_customerES_179',
       'VALUEMWHMETERINGDATA_customerES_180',
       'VALUEMWHMETERINGDATA_customerES_182',
       'VALUEMWHMETERINGDATA_customerES_183',
       'VALUEMWHMETERINGDATA_customerES_186',
       'VALUEMWHMETERINGDATA_customerES_188',
       'VALUEMWHMETERINGDATA_customerES_190',
       'VALUEMWHMETERINGDATA_customerES_199',
       'VALUEMWHMETERINGDATA_customerES_201',
       'VALUEMWHMETERINGDATA_customerES_202',
       'VALUEMWHMETERINGDATA_customerES_207',
       'VALUEMWHMETERINGDATA_customerES_209',
       'VALUEMWHMETERINGDATA_customerES_210',
       'VALUEMWHMETERINGDATA_customerES_213',
       'VALUEMWHMETERINGDATA_customerES_214',
       'VALUEMWHMETERINGDATA_customerES_216',
       'VALUEMWHMETERINGDATA_customerES_225',
       'VALUEMWHMETERINGDATA_customerES_226',
       'VALUEMWHMETERINGDATA_customerES_232',
       'VALUEMWHMETERINGDATA_customerES_234',
       'VALUEMWHMETERINGDATA_customerES_242',
       'VALUEMWHMETERINGDATA_customerES_244',
       'VALUEMWHMETERINGDATA_customerES_247',
       'VALUEMWHMETERINGDATA_customerES_263',
       'VALUEMWHMETERINGDATA_customerES_265',
       'VALUEMWHMETERINGDATA_customerES_266',
       'VALUEMWHMETERINGDATA_customerES_267',
       'VALUEMWHMETERINGDATA_customerES_269',
       'VALUEMWHMETERINGDATA_customerES_270',
       'VALUEMWHMETERINGDATA_customerES_273',
       'VALUEMWHMETERINGDATA_customerES_274',
       'VALUEMWHMETERINGDATA_customerES_282',
       'VALUEMWHMETERINGDATA_customerES_297',
       'VALUEMWHMETERINGDATA_customerES_298',
       'VALUEMWHMETERINGDATA_customerES_300',
       'VALUEMWHMETERINGDATA_customerES_307',
       'VALUEMWHMETERINGDATA_customerES_311',
       'VALUEMWHMETERINGDATA_customerES_312',
       'VALUEMWHMETERINGDATA_customerES_313',
       'VALUEMWHMETERINGDATA_customerES_334',
       'VALUEMWHMETERINGDATA_customerES_335',
       'VALUEMWHMETERINGDATA_customerES_336'],
      dtype='object')
Testing set columns: 98
Column difference: set()
Length of student solution: 744
Length of testing solution: 744
Student solution columns: 1696
Student solution columns: Index(['VALUEMWHMETERINGDATA_customerIT_1',
       'VALUEMWHMETERINGDATA_customerIT_2',
       'VALUEMWHMETERINGDATA_customerIT_3',
       'VALUEMWHMETERINGDATA_customerIT_4',
       'VALUEMWHMETERINGDATA_customerIT_5',
       'VALUEMWHMETERINGDATA_customerIT_6',
       'VALUEMWHMETERINGDATA_customerIT_7',
       'VALUEMWHMETERINGDATA_customerIT_8',
       'VALUEMWHMETERINGDATA_customerIT_13',
       'VALUEMWHMETERINGDATA_customerIT_14',
       ...
       'VALUEMWHMETERINGDATA_customerIT_2832',
       'VALUEMWHMETERINGDATA_customerIT_2836',
       'VALUEMWHMETERINGDATA_customerIT_2844',
       'VALUEMWHMETERINGDATA_customerIT_2845',
       'VALUEMWHMETERINGDATA_customerIT_2847',
       'VALUEMWHMETERINGDATA_customerIT_2848',
       'VALUEMWHMETERINGDATA_customerIT_2849',
       'VALUEMWHMETERINGDATA_customerIT_2850',
       'VALUEMWHMETERINGDATA_customerIT_2851',
       'VALUEMWHMETERINGDATA_customerIT_2852'],
      dtype='object', length=1696)
Testing set columns: 1696
Column difference: set()
Length of student solution: 744
Length of testing solution: 744
The team HANGUK_ML reached a forecast score of 1785468698.0

In [13]:
student_solution_path = join(
    student_path, "students_results_" + team_name + '_' + country + ".csv")
print(student_solution_path)
student_solution = pd.read_csv(
    student_solution_path, index_col=0, parse_dates=True, date_format=date_format)
student_solution

my_outputs/students_results_HANGUK_ML_IT.csv

,VALUEMWHMETERINGDATA_customerIT_1027,VALUEMWHMETERINGDATA_customerIT_2248,VALUEMWHMETERINGDATA_customerIT_1755,VALUEMWHMETERINGDATA_customerIT_387,VALUEMWHMETERINGDATA_customerIT_393,VALUEMWHMETERINGDATA_customerIT_2260,VALUEMWHMETERINGDATA_customerIT_1769,VALUEMWHMETERINGDATA_customerIT_2506,VALUEMWHMETERINGDATA_customerIT_1782,VALUEMWHMETERINGDATA_customerIT_378,...,VALUEMWHMETERINGDATA_customerIT_2292,VALUEMWHMETERINGDATA_customerIT_407,VALUEMWHMETERINGDATA_customerIT_1016,VALUEMWHMETERINGDATA_customerIT_1770,VALUEMWHMETERINGDATA_customerIT_2279,VALUEMWHMETERINGDATA_customerIT_1764,VALUEMWHMETERINGDATA_customerIT_1002,VALUEMWHMETERINGDATA_customerIT_2523,VALUEMWHMETERINGDATA_customerIT_1758,VALUEMWHMETERINGDATA_customerIT_2537
2024-08-01 00:00:00,0.000815,0.0,0.000314,0.191241,0.283035,0.003919,0.000223,0.139380,0.000719,0.041940,...,0.003897,0.582591,0.330784,0.000273,0.004320,0.000126,0.000720,0.000260,0.000436,0.207372
2024-08-01 01:00:00,0.000854,0.0,0.000283,0.210290,0.288403,0.003910,0.000208,0.229559,0.000667,0.048131,...,0.007937,0.565081,0.307351,0.000305,0.004427,0.000165,0.000819,0.000319,0.000437,0.179540
2024-08-01 02:00:00,0.000950,0.0,0.000278,0.222569,0.329723,0.003973,0.000203,0.238182,0.000712,0.045606,...,0.005617,0.541131,0.314273,0.000249,0.004875,0.000183,0.000770,0.000258,0.000431,0.201326
2024-08-01 03:00:00,0.000690,0.0,0.000242,0.249673,0.367797,0.003951,0.000185,0.196468,0.000685,0.048041,...,0.003503,0.554918,0.299384,0.000293,0.004727,0.000132,0.000461,0.000258,0.000434,0.223657
2024-08-01 04:00:00,0.000722,0.0,0.000230,0.393137,0.429629,0.003938,0.000209,0.319521,0.000668,0.046067,...,0.005412,0.540931,0.319925,0.000255,0.007615,0.000182,0.001835,0.000310,0.000449,0.271943
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-31 19:00:00,0.000843,0.0,0.000470,0.372091,0.566483,0.003782,0.000174,0.327585,0.000573,0.021241,...,0.037162,0.634933,0.298565,0.000318,0.008016,0.000112,0.000540,0.000334,0.000632,0.405361
2024-08-31 20:00:00,0.001111,0.0,0.000347,0.375789,0.557006,0.003931,0.000173,0.313066,0.000852,0.025736,...,0.038710,0.586573,0.305688,0.000368,0.013260,0.000118,0.000662,0.000314,0.000534,0.393959
2024-08-31 21:00:00,0.000749,0.0,0.000311,0.437820,0.543390,0.003922,0.000313,0.277896,0.000931,0.026395,...,0.021217,0.632820,0.297012,0.000316,0.012031,0.000114,0.001359,0.000305,0.000536,0.333553
2024-08-31 22:00:00,0.000775,0.0,0.000346,0.403833,0.412817,0.003904,0.000252,0.394040,0.000897,0.026507,...,0.058954,0.634493,0.218438,0.000316,0.019152,0.000101,0.000882,0.000336,0.000570,0.322832
2024-08-31 23:00:00,0.000710,0.0,0.000262,0.407235,0.369849,0.003882,0.000219,0.326159,0.000891,0.026484,...,0.056912,0.674008,0.197691,0.000308,0.019056,0.000088,0.001300,0.000267,0.000508,0.328088