In [1]:
import pandas as pd
import os
import re
import pandas as pd
import numpy as np
from os.path import join
from datetime import datetime
import pandas as pd
import numpy as np
from os.path import join

# depending on your IDE, you might need to add datathon_eth. in front of data
from my_data_og import DataLoader, SimpleEncoding

# depending on your IDE, you might need to add datathon_eth. in front of forecast_models
from forecast_og_models import SimpleModel

In [2]:
# Path to your folder
folder_path = 'outputs'

# Initialize lists to hold DataFrames
dfs_it = []
dfs_es = []

# Regex to match only non-duplicate files like 'IT_123.csv' or 'ES_456.csv'
valid_file_pattern = re.compile(r'^(IT|ES)_(\d+)\.csv$')

# Iterate over files in the folder
for filename in os.listdir(folder_path):
    if valid_file_pattern.match(filename):
        full_path = os.path.join(folder_path, filename)

        # Read CSV with datetime index
        df = pd.read_csv(full_path, index_col=0, parse_dates=True)

        # Append to the appropriate list
        if filename.startswith('IT_'):
            dfs_it.append(df)
        else:  # starts with ES_
            dfs_es.append(df)

# Combine all dataframes by column
df_it = pd.concat(dfs_it, axis=1)
df_es = pd.concat(dfs_es, axis=1)

In [3]:
team_name = "HANGUK_ML"

def main(zone: str, my_df, team_name):
    """

    Train and evaluate the models for IT and ES

    """
    country = zone
    # Inputs
    input_path = r"/Users/alexanders/Desktop/Downloads_Folder/OneDrive_2_4-5-2025/datasets2025"
    output_path = r"my_final_outputs"

    # Load Datasets
    loader = DataLoader(input_path)
    # features are holidays and temperature
    training_set, features, example_results = loader.load_data(zone)

    """
    EVERYTHING STARTING FROM HERE CAN BE MODIFIED.
    """
    team_name = "HANGUK_ML"
    # Data Manipulation and Training
    start_training = training_set.index.min()
    end_training = training_set.index.max()
    start_forecast, end_forecast = example_results.index[0], example_results.index[-1]

    range_forecast = pd.date_range(start=start_forecast, end=end_forecast, freq="1H")
    # forecast = pd.DataFrame(columns=training_set.columns, index=range_forecast)
    forecast = my_df[training_set.columns]

    # for costumer in training_set.columns.values:
    #     print(costumer)
    #     consumption = training_set.loc[:, costumer]
        
    #     feature_dummy = features['temp'].loc[start_training:]

    #     encoding = SimpleEncoding(
    #         consumption, feature_dummy, end_training, start_forecast, end_forecast
    #     )

    #     feature_past, feature_future, consumption_clean = (
    #         encoding.meta_encoding()
    #     )

    #     # Train
    #     model = SimpleModel()
    #     model.train(feature_past, consumption_clean)

    #     # Predict
    #     output = model.predict(feature_future)
    #     forecast[costumer] = output

    """
    END OF THE MODIFIABLE PART.
    """

    # test to make sure that the output has the expected shape.
    dummy_error = np.abs(forecast - example_results).sum().sum()
    assert np.all(forecast.columns == example_results.columns), (
        "Wrong header or header order."
    )
    assert np.all(forecast.index == example_results.index), (
        "Wrong index or index order."
    )
    assert isinstance(dummy_error, np.float64), "Wrong dummy_error type."
    assert forecast.isna().sum().sum() == 0, "NaN in forecast."
    # Your solution will be evaluated using
    # forecast_error = np.abs(forecast - testing_set).sum().sum(),
    # and then doing a weighted sum the two portfolios:
    # score = forecast_error_IT + 5 * forecast_error_ES

    forecast.to_csv(
        join(output_path, "students_results_" + team_name + "_" + country + ".csv")
    )
    return forecast

In [4]:
forecast_it = main(zone='IT', my_df=df_it, team_name=team_name)
forecast_it

/var/folders/3b/v9q3pbyx1r1gb74yk77xgx900000gq/T/ipykernel_31470/1584447321.py:28: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  range_forecast = pd.date_range(start=start_forecast, end=end_forecast, freq="1H")

,VALUEMWHMETERINGDATA_customerIT_1,VALUEMWHMETERINGDATA_customerIT_2,VALUEMWHMETERINGDATA_customerIT_3,VALUEMWHMETERINGDATA_customerIT_4,VALUEMWHMETERINGDATA_customerIT_5,VALUEMWHMETERINGDATA_customerIT_6,VALUEMWHMETERINGDATA_customerIT_7,VALUEMWHMETERINGDATA_customerIT_8,VALUEMWHMETERINGDATA_customerIT_13,VALUEMWHMETERINGDATA_customerIT_14,...,VALUEMWHMETERINGDATA_customerIT_2832,VALUEMWHMETERINGDATA_customerIT_2836,VALUEMWHMETERINGDATA_customerIT_2844,VALUEMWHMETERINGDATA_customerIT_2845,VALUEMWHMETERINGDATA_customerIT_2847,VALUEMWHMETERINGDATA_customerIT_2848,VALUEMWHMETERINGDATA_customerIT_2849,VALUEMWHMETERINGDATA_customerIT_2850,VALUEMWHMETERINGDATA_customerIT_2851,VALUEMWHMETERINGDATA_customerIT_2852
2024-08-01 00:00:00,0.001932,0.000882,0.181204,0.462359,0.001670,0.316828,0.212403,0.025316,0.002672,0.001782,...,0.005046,0.070378,0.000549,2.302734,0.035155,0.006855,0.005243,0.061807,0.000133,0.031759
2024-08-01 01:00:00,0.000274,0.000950,0.202876,0.435892,0.003348,0.284867,0.177757,0.041546,0.002795,0.002167,...,0.005090,0.083196,0.000718,2.072714,0.036258,0.006687,0.005740,0.057734,0.000744,0.020796
2024-08-01 02:00:00,0.000668,0.000513,0.195306,0.426013,0.002810,0.298421,0.163757,0.034646,0.002839,0.002219,...,0.002925,0.079638,0.000603,2.308071,0.034895,0.006025,0.007240,0.059975,0.000906,0.018696
2024-08-01 03:00:00,0.001367,0.000933,0.194591,0.435872,0.001681,0.283844,0.157498,0.025293,0.002825,0.001994,...,0.005243,0.084768,0.000683,2.150324,0.035235,0.006202,0.004991,0.054781,0.000422,0.019985
2024-08-01 04:00:00,0.003268,0.001115,0.190363,0.402430,0.003191,0.296579,0.171167,0.054368,0.002869,0.002265,...,0.005334,0.102186,0.000480,2.323963,0.035375,0.006358,0.007014,0.053276,0.001640,0.022081
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-31 19:00:00,0.004524,0.015198,0.203912,0.244851,0.010043,0.168133,0.209566,0.020213,0.002918,0.001569,...,0.005205,0.108627,0.001408,1.649645,0.040722,0.007283,0.004842,0.073566,0.000620,0.019042
2024-08-31 20:00:00,0.003139,0.007035,0.194201,0.336350,0.002097,0.201143,0.211069,0.026542,0.002912,0.001996,...,0.004265,0.116716,0.001460,1.864070,0.041974,0.007181,0.005719,0.066652,0.001076,0.019416
2024-08-31 21:00:00,0.002290,0.002754,0.193916,0.373430,0.000866,0.199956,0.195423,0.029079,0.002845,0.001920,...,0.009913,0.118290,0.003574,1.803777,0.039995,0.006780,0.004403,0.063608,0.001209,0.017823
2024-08-31 22:00:00,0.003556,0.011463,0.195533,0.347351,0.015511,0.196871,0.220079,0.032119,0.002887,0.001641,...,0.010954,0.121428,0.004157,1.811571,0.042694,0.007366,0.005620,0.056482,0.000824,0.022343
2024-08-31 23:00:00,0.002806,0.017910,0.177845,0.409286,0.014410,0.201280,0.217143,0.019534,0.003005,0.001506,...,0.013126,0.107488,0.004372,1.621168,0.040302,0.007548,0.008845,0.065977,0.000991,0.021110

In [5]:
forecast_es = main(zone='ES', my_df=df_es, team_name=team_name)
forecast_es

/var/folders/3b/v9q3pbyx1r1gb74yk77xgx900000gq/T/ipykernel_31470/1584447321.py:28: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  range_forecast = pd.date_range(start=start_forecast, end=end_forecast, freq="1H")

,VALUEMWHMETERINGDATA_customerES_1,VALUEMWHMETERINGDATA_customerES_2,VALUEMWHMETERINGDATA_customerES_5,VALUEMWHMETERINGDATA_customerES_11,VALUEMWHMETERINGDATA_customerES_19,VALUEMWHMETERINGDATA_customerES_30,VALUEMWHMETERINGDATA_customerES_31,VALUEMWHMETERINGDATA_customerES_39,VALUEMWHMETERINGDATA_customerES_40,VALUEMWHMETERINGDATA_customerES_44,...,VALUEMWHMETERINGDATA_customerES_297,VALUEMWHMETERINGDATA_customerES_298,VALUEMWHMETERINGDATA_customerES_300,VALUEMWHMETERINGDATA_customerES_307,VALUEMWHMETERINGDATA_customerES_311,VALUEMWHMETERINGDATA_customerES_312,VALUEMWHMETERINGDATA_customerES_313,VALUEMWHMETERINGDATA_customerES_334,VALUEMWHMETERINGDATA_customerES_335,VALUEMWHMETERINGDATA_customerES_336
2024-08-01 00:00:00,0.001112,0.000139,0.022273,0.020370,3.082833,0.015622,0.006362,0.085236,0.041503,0.076010,...,0.008825,1.102922,0.003942,2.004439,0.135572,0.003531,0.027683,0.052869,0.027916,0.136876
2024-08-01 01:00:00,0.001545,0.000231,0.022910,0.019932,3.031257,0.016108,0.006454,0.086591,0.040539,0.075502,...,0.007123,1.098390,0.003775,1.647362,0.108615,0.004409,0.032838,0.031133,0.026959,0.156864
2024-08-01 02:00:00,0.001740,0.000203,0.021643,0.021465,3.107730,0.015241,0.005885,0.155572,0.042450,0.085260,...,0.006783,1.101998,0.003315,1.772872,0.160863,0.004586,0.038473,0.051002,0.025568,0.148842
2024-08-01 03:00:00,0.002034,0.000246,0.024716,0.018598,3.046230,0.024621,0.006456,0.213295,0.044702,0.098411,...,0.007115,1.078395,0.003616,2.102226,0.198137,0.005106,0.039873,0.049824,0.025348,0.167505
2024-08-01 04:00:00,0.001398,0.000119,0.024042,0.026208,3.009387,0.022929,0.006704,0.246551,0.043410,0.090442,...,0.007809,1.103906,0.003334,2.530491,0.123386,0.006676,0.048136,0.046980,0.024691,0.177338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-31 19:00:00,0.001384,0.000166,0.023792,0.021666,2.083657,0.014767,0.007064,0.084786,0.025139,0.079229,...,0.008014,1.102792,0.003882,1.023127,0.081560,0.005872,0.039384,0.060226,0.025346,0.107484
2024-08-31 20:00:00,0.001481,0.000170,0.022869,0.025111,2.069520,0.016657,0.007253,0.074493,0.026410,0.066961,...,0.010178,1.019971,0.003546,1.603679,0.113702,0.004458,0.021759,0.053097,0.023541,0.126779
2024-08-31 21:00:00,0.001745,0.000190,0.024646,0.021621,1.973580,0.019494,0.008476,0.070645,0.026696,0.064557,...,0.009157,0.530609,0.003644,1.550535,0.126150,0.005076,0.027948,0.048797,0.023234,0.128125
2024-08-31 22:00:00,0.002049,0.000238,0.022383,0.023594,2.356282,0.018629,0.008458,0.064076,0.026131,0.054090,...,0.006114,0.902513,0.003971,1.476234,0.080737,0.005441,0.026798,0.030175,0.021483,0.127928
2024-08-31 23:00:00,0.002542,0.000314,0.022811,0.019062,2.501794,0.022021,0.008207,0.072091,0.027867,0.072288,...,0.007290,0.792733,0.003849,1.721110,0.094619,0.005007,0.026778,0.026511,0.025742,0.116717

In [6]:
import pandas as pd
import numpy as np
from os.path import join
from datetime import datetime

date_format = '%Y-%m-%d %H:%M:%S'
student_path = r"my_final_outputs"
testing_set_path = r"/Users/alexanders/Desktop/Downloads_Folder/OneDrive_2_4-5-2025/datasets2025"

absolute_error = {}
portfolio_error = {} 

for team_name in [team_name]:

    try:
        for country in ['ES', 'IT']:
            student_solution_path = join(
                student_path, "students_results_" + team_name + '_' + country + ".csv")
            student_solution = pd.read_csv(
                student_solution_path, index_col=0, parse_dates=True, date_format=date_format)
            testing_set_fullpath = join(
                testing_set_path, "example_set_" + country + ".csv")
            testing_set = pd.read_csv(
                testing_set_fullpath, index_col=0, parse_dates=True, date_format=date_format)

            country_error = (student_solution - testing_set).abs().sum().sum()
            portfolio_country_error = (student_solution - testing_set).sum(axis=1).abs().sum() 

            assert np.all(student_solution.columns ==
                          testing_set.columns), 'Wrong header or header order for team ' + team_name
            assert np.all(student_solution.index ==
                          testing_set.index), 'Wrong index or index order for team ' + team_name
            assert isinstance(
                country_error, np.float64), 'Wrong error type for team ' + team_name
            assert student_solution.isna().sum().sum(
            ) == 0, 'NaN in forecast for team ' + team_name

            absolute_error[country] = country_error
            portfolio_error[country] = portfolio_country_error

        forecast_score = (
            1.0*absolute_error['IT'] + 5.0*absolute_error['ES'] + 
            10.0*portfolio_error['IT'] + 50.0*portfolio_error['ES']
        )
        print('The team ' + team_name + ' reached a forecast score of ' +
              str(np.round(forecast_score, 0)))
    except Exception as e:
        print('Error for team ' + team_name)
        print(e)
print('=== End of the script, %s. ===' % (str(datetime.now())))

The team HANGUK_ML reached a forecast score of 1785468698.0
=== End of the script, 2025-04-06 11:09:26.085012. ===